pirate_map = '''
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVssssssssVVVVVVVVVVVVVVVVVVVVVVVVV
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVsssSSsssVVVVVVVVVVVVVVVVVVVVVVVVV
VVVVVVVVVVVVVVVVVLLLLLLLLLLLLLLLLLVVVVVVVVVSSSPpPpSSPpPpSSSSVVVVVVVVVVVVVVVVVVVV
VVVVVVVVVVVVVLLLL                LLLLLVVVVVVSSSSSSSSSSSSSSSVLLLLLVVVVVVVVVVVVVVV
VVVVVVVVVVVVLL                       LLLLLVVVVSSSSSSSSSSVVVLL   LLLLVVVVVVVVVVVV
VVVVVVVVVVLLL      ********          **  LLLLVVVVVVVVVVVVVLL        LLLVVVVVVVVV
VVVVVVVVVLL    ****        **********       LLVVVVVVVVVVVVL   TTTTT   LLVVVVVVVV
VVVVVVVVLL   **                              LLLVVVVVVVVVVL   TTTTTTT  LLVVVVVVV
VVVVVVVLL   *     MMMMM       TTTT TTTTT       LLVVVVVVVVVLLL   TTTTT   LVVVVVVV
VVVVVVLL  **   MMMM   MM     tt  tttTTTTTTT     LLVVVVVVVVVVLLL       LLLVVVVVVV
VVVVVVL   *   MM       MM   tttttTtttTTTT TTTT   LLVVVVVVVVVVVLLLLLLLLLVVVVVVVVV
VVVVVVL  *    M         M tTTtT TTtttTTTTTttttTT   LVVVVVVVVVVVVVVVVVVVVVVVVVVVV
VVVVVVL  *   MM      MMMMMT tttttttttttTT tTT tT    LLVVVVVVVVVVVVVVVVVVVVVVVVVV
VVVVVVLL *   M    MMMM MMMMMTtttttTtttttt  tttt      LLLVVVVVVVVVVVVVVVVVVVVVVVV
VVVVVVVLL *  M   M         MM     TTtTT t               LLLLLVVVVVVVVVVVVVVVVVVV
VVVVVVVVL  * M  MM          M       ttttt    **********      LLLVVVVVVVVVVVVVVVV
VVVVVVVVLL  **  M                       *****          ***     LLLLVVVVVVVVVVVVV
VVVVVVVVVLL   ***  *********************     vvvvvvv      *       LLVVVVVVVVVVVV
VVVVVVVVVVLLL   ***                     vvvvvvvvvvvvvv     X*X     LLVVVVVVVVVVV
VVVVVVVVVVVVLLL                         vvvvvvvvvvvvvv      X       LLVVVVVVVVVV
VVVVVVVVVVVVVVLLL                       vvvvvvvvvvvvv      X X       LVVVVVVVVVV
VVVVVVVVVVVVVVVVVLLLLL                       vvvvvvv               LLLVVVVVVVVVV
VVVVVVVVVVVVVVVVVVVVVLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL        LLLLLLLVVVVVVVVVVVV
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVLLLLLLLLLLVVVVVVVVVVVVVVVVVV
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
'''


colors = {
    '*': '\033[38;2;61;74;78m',  # #3D4A4E (Path, Pirates)
    'S': '\033[38;2;126;122;103m',  # #7E7A67 (Ship)
    'P': '\033[38;2;61;74;78m',  # #3D4A4E (Pirates)
    'p': '\033[38;2;61;74;78m',  # #3D4A4E (Pirates)
    'L': '\033[38;2;95;75;46m',  # #5F4B2E (Land)
    'V': '\033[38;2;28;116;119m',  # #1C7477 (Ocean)
    'v': '\033[38;2;23;80;114m',  # #175072 (Lake)
    'X': '\033[38;2;131;18;45m',  # #83122D (Treasure)
    'T': '\033[38;2;61;125;86m',  # #3D7D56 (Trees)
    't': '\033[38;2;61;125;86m',  # #3D7D56 (Trees)
    'M': '\033[38;2;95;75;46m',  # #5F4B2E (Mountains)
    ' ': '\033[38;2;248;245;232m'  # #F8F5E8 (Whitespace)
}
reset = '\033[0m'

for line in pirate_map.split('\n'):
    for char in line:
        print(f"{colors.get(char, '')}{char}{reset}", end='')
    print()
